apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lwcluster
  region: ap-south-1

nodeGroups:
   - name: ng1
     desiredCapacity: 5
     instanceType: t2.micro
     ssh:
        publicKeyName: docker
   - name: ng2
     desiredCapacity: 3
     instanceType: t2.large
     ssh:
        publicKeyName: docker
